package com.grape.models;
// Generated Dec 9, 2016 9:59:15 AM by Hibernate Tools 3.4.0.CR1


import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NbatableId generated by hbm2java
 */
@Entity
@Table(name = "nba_schedtable", catalog = "grape_db")
public class NbaSchedule  implements java.io.Serializable {


     private String awayTeam;
     private String homeTeam;
     private String date;
     private Integer id;
     private String time;
     private Integer awayScore;
     private Integer homeScore;
     private String box;
     private String overtime;
     private String notes;

    @Id
    @Column(name="id")
    public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="awayTeam", length=65535)
    public String getAwayTeam() {
        return this.awayTeam;
    }
    
    public void setAwayTeam(String awayTeam) {
        this.awayTeam = awayTeam;
    }

    @Column(name="homeTeam")
    public String getHomeTeam() {
        return this.homeTeam;
    }
    
    public void setHomeTeam(String homeTeam) {
        this.homeTeam = homeTeam;
    }

    @Column(name="date")
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    
    @Column(name="homeScore")
    public Integer getHomeScore() {
        return this.homeScore;
    }
    
    public void setHomeScore(Integer homeScore) {
        this.homeScore = homeScore;
    }
    
    @Column(name="awayScore")
    public Integer getAwayScore() {
        return this.awayScore;
    }
    
    public void setAwayScore(Integer awayScore) {
        this.awayScore = awayScore;
    }
    
    @Column(name="time")
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }
    
    @Column(name="box")
    public String getBox() {
        return this.box;
    }
    
    public void setBox(String box) {
        this.box = box;
    }
    
    @Column(name="Ot")
    public String getOvertime() {
        return this.overtime;
    }
    
    public void setOvertime(String overtime) {
        this.overtime = overtime;
    }
    
    @Column(name="Notes")
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NbaSchedule) ) return false;
		 NbaSchedule castOther = ( NbaSchedule ) other; 
         
		 return ( (this.getAwayTeam()==castOther.getAwayTeam()) || ( this.getAwayTeam()!=null && castOther.getAwayTeam()!=null && this.getAwayTeam().equals(castOther.getAwayTeam()) ) )
 && ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getHomeTeam()==castOther.getHomeTeam()) || ( this.getHomeTeam()!=null && castOther.getHomeTeam()!=null && this.getHomeTeam().equals(castOther.getHomeTeam()) ) )
 && ( (this.getHomeScore()==castOther.getHomeScore()) || ( this.getHomeScore()!=null && castOther.getHomeScore()!=null && this.getHomeScore().equals(castOther.getHomeScore()) ) )
 && ( (this.getHomeScore()==castOther.getAwayScore()) || ( this.getAwayScore()!=null && castOther.getAwayScore()!=null && this.getAwayScore().equals(castOther.getAwayScore()) ) )
 && ( (this.getOvertime()==castOther.getOvertime()) || ( this.getOvertime()!=null && castOther.getOvertime()!=null && this.getOvertime().equals(castOther.getOvertime()) ) )
 && ( (this.getTime()==castOther.getTime()) || ( this.getTime()!=null && castOther.getTime()!=null && this.getTime().equals(castOther.getTime()) ) )
 && ( (this.getBox()==castOther.getBox()) || ( this.getBox()!=null && castOther.getBox()!=null && this.getBox().equals(castOther.getBox()) ) )
 && ( (this.getNotes()==castOther.getNotes()) || ( this.getNotes()!=null && castOther.getNotes()!=null && this.getNotes().equals(castOther.getNotes()) ) )
 && ( (this.getDate()==castOther.getDate()) || ( this.getDate()!=null && castOther.getDate()!=null && this.getDate().equals(castOther.getDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getAwayTeam() == null ? 0 : this.getAwayTeam().hashCode() );
         result = 37 * result + ( getHomeTeam() == null ? 0 : this.getHomeTeam().hashCode() );
         result = 37 * result + ( getDate() == null ? 0 : this.getDate().hashCode() );
         result = 37 * result + ( getHomeScore() == null ? 0 : this.getHomeScore().hashCode() );
         result = 37 * result + ( getAwayScore() == null ? 0 : this.getAwayScore().hashCode() );
         result = 37 * result + ( getOvertime() == null ? 0 : this.getOvertime().hashCode() );
         result = 37 * result + ( getTime() == null ? 0 : this.getTime().hashCode() );
         result = 37 * result + ( getBox() == null ? 0 : this.getBox().hashCode() );
         result = 37 * result + ( getNotes() == null ? 0 : this.getNotes().hashCode() );
         return result;
   }   


}


