package com.grape.models;
// Generated Dec 9, 2016 9:59:15 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NbatableId generated by hbm2java
 */
@Entity
@Table(name = "nbatable", catalog = "grape_db")
public class Nbatable  implements java.io.Serializable {


     private String team;
     private Integer gp;
     private Integer w;
     private Integer l;
     private Integer min;
     private Double offRtg;
     private Double defRtg;
     private Double netRtg;
     private Double ast;
     private Double astto;
     private Double astRatio;
     private Double oreb;
     private Double dreb;
     private Double reb;
     private Double toRatio;
     private Double efg;
     private Double ts;
     private Double pace;
     private Double pie;
     private Integer id;

    @Column(name="id")
    @Id
    public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="Team", length=65535)
    public String getTeam() {
        return this.team;
    }
    
    public void setTeam(String team) {
        this.team = team;
    }

    @Column(name="GP")
    public Integer getGp() {
        return this.gp;
    }
    
    public void setGp(Integer gp) {
        this.gp = gp;
    }


    @Column(name="W")
    public Integer getW() {
        return this.w;
    }
    
    public void setW(Integer w) {
        this.w = w;
    }


    @Column(name="L")
    public Integer getL() {
        return this.l;
    }
    
    public void setL(Integer l) {
        this.l = l;
    }


    @Column(name="MIN")
    public Integer getMin() {
        return this.min;
    }
    
    public void setMin(Integer min) {
        this.min = min;
    }


    @Column(name="OffRtg", precision=22, scale=0)
    public Double getOffRtg() {
        return this.offRtg;
    }
    
    public void setOffRtg(Double offRtg) {
        this.offRtg = offRtg;
    }


    @Column(name="DefRtg", precision=22, scale=0)
    public Double getDefRtg() {
        return this.defRtg;
    }
    
    public void setDefRtg(Double defRtg) {
        this.defRtg = defRtg;
    }


    @Column(name="NetRtg", precision=22, scale=0)
    public Double getNetRtg() {
        return this.netRtg;
    }
    
    public void setNetRtg(Double netRtg) {
        this.netRtg = netRtg;
    }


    @Column(name="AST", precision=22, scale=0)
    public Double getAst() {
        return this.ast;
    }
    
    public void setAst(Double ast) {
        this.ast = ast;
    }


    @Column(name="ASTTO", precision=22, scale=0)
    public Double getAstto() {
        return this.astto;
    }
    
    public void setAstto(Double astto) {
        this.astto = astto;
    }


    @Column(name="ASTRatio", precision=22, scale=0)
    public Double getAstRatio() {
        return this.astRatio;
    }
    
    public void setAstRatio(Double astRatio) {
        this.astRatio = astRatio;
    }


    @Column(name="OREB", precision=22, scale=0)
    public Double getOreb() {
        return this.oreb;
    }
    
    public void setOreb(Double oreb) {
        this.oreb = oreb;
    }


    @Column(name="DREB", precision=22, scale=0)
    public Double getDreb() {
        return this.dreb;
    }
    
    public void setDreb(Double dreb) {
        this.dreb = dreb;
    }


    @Column(name="REB", precision=22, scale=0)
    public Double getReb() {
        return this.reb;
    }
    
    public void setReb(Double reb) {
        this.reb = reb;
    }


    @Column(name="TORatio", precision=22, scale=0)
    public Double getToRatio() {
        return this.toRatio;
    }
    
    public void setToRatio(Double toRatio) {
        this.toRatio = toRatio;
    }


    @Column(name="eFG", precision=22, scale=0)
    public Double getEfg() {
        return this.efg;
    }
    
    public void setEfg(Double efg) {
        this.efg = efg;
    }


    @Column(name="TS", precision=22, scale=0)
    public Double getTs() {
        return this.ts;
    }
    
    public void setTs(Double ts) {
        this.ts = ts;
    }


    @Column(name="PACE", precision=22, scale=0)
    public Double getPace() {
        return this.pace;
    }
    
    public void setPace(Double pace) {
        this.pace = pace;
    }


    @Column(name="PIE", precision=22, scale=0)
    public Double getPie() {
        return this.pie;
    }
    
    public void setPie(Double pie) {
        this.pie = pie;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Nbatable) ) return false;
		 Nbatable castOther = ( Nbatable ) other; 
         
		 return ( (this.getTeam()==castOther.getTeam()) || ( this.getTeam()!=null && castOther.getTeam()!=null && this.getTeam().equals(castOther.getTeam()) ) )
&& ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getGp()==castOther.getGp()) || ( this.getGp()!=null && castOther.getGp()!=null && this.getGp().equals(castOther.getGp()) ) )
 && ( (this.getW()==castOther.getW()) || ( this.getW()!=null && castOther.getW()!=null && this.getW().equals(castOther.getW()) ) )
 && ( (this.getL()==castOther.getL()) || ( this.getL()!=null && castOther.getL()!=null && this.getL().equals(castOther.getL()) ) )
 && ( (this.getMin()==castOther.getMin()) || ( this.getMin()!=null && castOther.getMin()!=null && this.getMin().equals(castOther.getMin()) ) )
 && ( (this.getOffRtg()==castOther.getOffRtg()) || ( this.getOffRtg()!=null && castOther.getOffRtg()!=null && this.getOffRtg().equals(castOther.getOffRtg()) ) )
 && ( (this.getDefRtg()==castOther.getDefRtg()) || ( this.getDefRtg()!=null && castOther.getDefRtg()!=null && this.getDefRtg().equals(castOther.getDefRtg()) ) )
 && ( (this.getNetRtg()==castOther.getNetRtg()) || ( this.getNetRtg()!=null && castOther.getNetRtg()!=null && this.getNetRtg().equals(castOther.getNetRtg()) ) )
 && ( (this.getAst()==castOther.getAst()) || ( this.getAst()!=null && castOther.getAst()!=null && this.getAst().equals(castOther.getAst()) ) )
 && ( (this.getAstto()==castOther.getAstto()) || ( this.getAstto()!=null && castOther.getAstto()!=null && this.getAstto().equals(castOther.getAstto()) ) )
 && ( (this.getAstRatio()==castOther.getAstRatio()) || ( this.getAstRatio()!=null && castOther.getAstRatio()!=null && this.getAstRatio().equals(castOther.getAstRatio()) ) )
 && ( (this.getOreb()==castOther.getOreb()) || ( this.getOreb()!=null && castOther.getOreb()!=null && this.getOreb().equals(castOther.getOreb()) ) )
 && ( (this.getDreb()==castOther.getDreb()) || ( this.getDreb()!=null && castOther.getDreb()!=null && this.getDreb().equals(castOther.getDreb()) ) )
 && ( (this.getReb()==castOther.getReb()) || ( this.getReb()!=null && castOther.getReb()!=null && this.getReb().equals(castOther.getReb()) ) )
 && ( (this.getToRatio()==castOther.getToRatio()) || ( this.getToRatio()!=null && castOther.getToRatio()!=null && this.getToRatio().equals(castOther.getToRatio()) ) )
 && ( (this.getEfg()==castOther.getEfg()) || ( this.getEfg()!=null && castOther.getEfg()!=null && this.getEfg().equals(castOther.getEfg()) ) )
 && ( (this.getTs()==castOther.getTs()) || ( this.getTs()!=null && castOther.getTs()!=null && this.getTs().equals(castOther.getTs()) ) )
 && ( (this.getPace()==castOther.getPace()) || ( this.getPace()!=null && castOther.getPace()!=null && this.getPace().equals(castOther.getPace()) ) )
 && ( (this.getPie()==castOther.getPie()) || ( this.getPie()!=null && castOther.getPie()!=null && this.getPie().equals(castOther.getPie()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getTeam() == null ? 0 : this.getTeam().hashCode() );
         result = 37 * result + ( getGp() == null ? 0 : this.getGp().hashCode() );
         result = 37 * result + ( getW() == null ? 0 : this.getW().hashCode() );
         result = 37 * result + ( getL() == null ? 0 : this.getL().hashCode() );
         result = 37 * result + ( getMin() == null ? 0 : this.getMin().hashCode() );
         result = 37 * result + ( getOffRtg() == null ? 0 : this.getOffRtg().hashCode() );
         result = 37 * result + ( getDefRtg() == null ? 0 : this.getDefRtg().hashCode() );
         result = 37 * result + ( getNetRtg() == null ? 0 : this.getNetRtg().hashCode() );
         result = 37 * result + ( getAst() == null ? 0 : this.getAst().hashCode() );
         result = 37 * result + ( getAstto() == null ? 0 : this.getAstto().hashCode() );
         result = 37 * result + ( getAstRatio() == null ? 0 : this.getAstRatio().hashCode() );
         result = 37 * result + ( getOreb() == null ? 0 : this.getOreb().hashCode() );
         result = 37 * result + ( getDreb() == null ? 0 : this.getDreb().hashCode() );
         result = 37 * result + ( getReb() == null ? 0 : this.getReb().hashCode() );
         result = 37 * result + ( getToRatio() == null ? 0 : this.getToRatio().hashCode() );
         result = 37 * result + ( getEfg() == null ? 0 : this.getEfg().hashCode() );
         result = 37 * result + ( getTs() == null ? 0 : this.getTs().hashCode() );
         result = 37 * result + ( getPace() == null ? 0 : this.getPace().hashCode() );
         result = 37 * result + ( getPie() == null ? 0 : this.getPie().hashCode() );
         return result;
   }   


}


