package com.grape.models;
// Generated Dec 9, 2016 9:59:15 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NcaatableId generated by hbm2java
 */
@Entity
@Table(name = "ncaatable", catalog = "grape_db")
public class Ncaatable implements java.io.Serializable {

	private Integer rank;
	private String team;
	private String conf;
	private String WL;
	private Double adjEm;
	private Double adjO;
	private Integer adjO2;
	private Double adjD;
	private Integer adjD2;
	private Double adjT;
	private Integer adjT2;
	private Double luck;
	private Integer luck2;
	private Double strengthOfScheduleAdjEm;
	private Integer strengthOfScheduleAdjEm2;
	private Double strengthOfScheduleOppO;
	private Integer strengthOfScheduleOppO2;
	private Double strengthOfScheduleOppD;
	private Integer strengthOfScheduleOppD2;
	private Double ncsosAdjEm;
	private Integer ncsosAdjEm2;
    private Integer id;
	
	@Column(name="id")
    @Id
    public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Rank")
	public Integer getRank() {
		return this.rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

	@Column(name = "Team", length = 65535)
	public String getTeam() {
		return this.team;
	}

	public void setTeam(String team) {
		this.team = team;
	}

	@Column(name = "Conf", length = 65535)
	public String getConf() {
		return this.conf;
	}

	public void setConf(String conf) {
		this.conf = conf;
	}

	@Column(name = "WinLoss", length = 65535)
	public String getWL() {
		return this.WL;
	}

	public void setWL(String WL) {
		this.WL = WL;
	}

	@Column(name = "AdjEM", precision = 22, scale = 0)
	public Double getAdjEm() {
		return this.adjEm;
	}

	public void setAdjEm(Double adjEm) {
		this.adjEm = adjEm;
	}

	@Column(name = "AdjO", precision = 22, scale = 0)
	public Double getAdjO() {
		return this.adjO;
	}

	public void setAdjO(Double adjO) {
		this.adjO = adjO;
	}

	@Column(name = "AdjO2")
	public Integer getAdjO2() {
		return this.adjO2;
	}

	public void setAdjO2(Integer adjO2) {
		this.adjO2 = adjO2;
	}

	@Column(name = "AdjD", precision = 22, scale = 0)
	public Double getAdjD() {
		return this.adjD;
	}

	public void setAdjD(Double adjD) {
		this.adjD = adjD;
	}

	@Column(name = "AdjD2")
	public Integer getAdjD2() {
		return this.adjD2;
	}

	public void setAdjD2(Integer adjD2) {
		this.adjD2 = adjD2;
	}

	@Column(name = "AdjT", precision = 22, scale = 0)
	public Double getAdjT() {
		return this.adjT;
	}

	public void setAdjT(Double adjT) {
		this.adjT = adjT;
	}

	@Column(name = "AdjT2")
	public Integer getAdjT2() {
		return this.adjT2;
	}

	public void setAdjT2(Integer adjT2) {
		this.adjT2 = adjT2;
	}

	@Column(name = "Luck", precision = 22, scale = 0)
	public Double getLuck() {
		return this.luck;
	}

	public void setLuck(Double luck) {
		this.luck = luck;
	}

	@Column(name = "Luck2")
	public Integer getLuck2() {
		return this.luck2;
	}

	public void setLuck2(Integer luck2) {
		this.luck2 = luck2;
	}

	@Column(name = "SSAdjEM", precision = 22, scale = 0)
	public Double getStrengthOfScheduleAdjEm() {
		return this.strengthOfScheduleAdjEm;
	}

	public void setStrengthOfScheduleAdjEm(Double strengthOfScheduleAdjEm) {
		this.strengthOfScheduleAdjEm = strengthOfScheduleAdjEm;
	}

	@Column(name = "SSAdjEM2")
	public Integer getStrengthOfScheduleAdjEm2() {
		return this.strengthOfScheduleAdjEm2;
	}

	public void setStrengthOfScheduleAdjEm2(Integer strengthOfScheduleAdjEm2) {
		this.strengthOfScheduleAdjEm2 = strengthOfScheduleAdjEm2;
	}

	@Column(name = "SSOppO", precision = 22, scale = 0)
	public Double getStrengthOfScheduleOppO() {
		return this.strengthOfScheduleOppO;
	}

	public void setStrengthOfScheduleOppO(Double strengthOfScheduleOppO) {
		this.strengthOfScheduleOppO = strengthOfScheduleOppO;
	}

	@Column(name = "SSOppO2")
	public Integer getStrengthOfScheduleOppO2() {
		return this.strengthOfScheduleOppO2;
	}

	public void setStrengthOfScheduleOppO2(Integer strengthOfScheduleOppO2) {
		this.strengthOfScheduleOppO2 = strengthOfScheduleOppO2;
	}

	@Column(name = "SSOppD", precision = 22, scale = 0)
	public Double getStrengthOfScheduleOppD() {
		return this.strengthOfScheduleOppD;
	}

	public void setStrengthOfScheduleOppD(Double strengthOfScheduleOppD) {
		this.strengthOfScheduleOppD = strengthOfScheduleOppD;
	}

	@Column(name = "SSOppD2")
	public Integer getStrengthOfScheduleOppD2() {
		return this.strengthOfScheduleOppD2;
	}

	public void setStrengthOfScheduleOppD2(Integer strengthOfScheduleOppD2) {
		this.strengthOfScheduleOppD2 = strengthOfScheduleOppD2;
	}

	@Column(name = "NCSOSAdjEM", precision = 22, scale = 0)
	public Double getNcsosAdjEm() {
		return this.ncsosAdjEm;
	}

	public void setNcsosAdjEm(Double ncsosAdjEm) {
		this.ncsosAdjEm = ncsosAdjEm;
	}

	@Column(name = "NCSOSAdjEM2")
	public Integer getNcsosAdjEm2() {
		return this.ncsosAdjEm2;
	}

	public void setNcsosAdjEm2(Integer ncsosAdjEm2) {
		this.ncsosAdjEm2 = ncsosAdjEm2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Ncaatable))
			return false;
		Ncaatable castOther = (Ncaatable) other;

		return ((this.getRank() == castOther.getRank()) || (this.getRank() != null
				&& castOther.getRank() != null && this.getRank().equals(
				castOther.getRank())))
				&& ((this.getTeam() == castOther.getTeam()) || (this.getTeam() != null
						&& castOther.getTeam() != null && this.getTeam()
						.equals(castOther.getTeam())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null
						&& castOther.getId() != null && this.getId()
						.equals(castOther.getId())))
				&& ((this.getConf() == castOther.getConf()) || (this.getConf() != null
						&& castOther.getConf() != null && this.getConf()
						.equals(castOther.getConf())))
				&& ((this.getWL() == castOther.getWL()) || (this.getWL() != null
						&& castOther.getWL() != null && this.getWL().equals(
						castOther.getWL())))
				&& ((this.getAdjEm() == castOther.getAdjEm()) || (this
						.getAdjEm() != null && castOther.getAdjEm() != null && this
						.getAdjEm().equals(castOther.getAdjEm())))
				&& ((this.getAdjO() == castOther.getAdjO()) || (this.getAdjO() != null
						&& castOther.getAdjO() != null && this.getAdjO()
						.equals(castOther.getAdjO())))
				&& ((this.getAdjO2() == castOther.getAdjO2()) || (this
						.getAdjO2() != null && castOther.getAdjO2() != null && this
						.getAdjO2().equals(castOther.getAdjO2())))
				&& ((this.getAdjD() == castOther.getAdjD()) || (this.getAdjD() != null
						&& castOther.getAdjD() != null && this.getAdjD()
						.equals(castOther.getAdjD())))
				&& ((this.getAdjD2() == castOther.getAdjD2()) || (this
						.getAdjD2() != null && castOther.getAdjD2() != null && this
						.getAdjD2().equals(castOther.getAdjD2())))
				&& ((this.getAdjT() == castOther.getAdjT()) || (this.getAdjT() != null
						&& castOther.getAdjT() != null && this.getAdjT()
						.equals(castOther.getAdjT())))
				&& ((this.getAdjT2() == castOther.getAdjT2()) || (this
						.getAdjT2() != null && castOther.getAdjT2() != null && this
						.getAdjT2().equals(castOther.getAdjT2())))
				&& ((this.getLuck() == castOther.getLuck()) || (this.getLuck() != null
						&& castOther.getLuck() != null && this.getLuck()
						.equals(castOther.getLuck())))
				&& ((this.getLuck2() == castOther.getLuck2()) || (this
						.getLuck2() != null && castOther.getLuck2() != null && this
						.getLuck2().equals(castOther.getLuck2())))
				&& ((this.getStrengthOfScheduleAdjEm() == castOther
						.getStrengthOfScheduleAdjEm()) || (this
						.getStrengthOfScheduleAdjEm() != null
						&& castOther.getStrengthOfScheduleAdjEm() != null && this
						.getStrengthOfScheduleAdjEm().equals(
								castOther.getStrengthOfScheduleAdjEm())))
				&& ((this.getStrengthOfScheduleAdjEm2() == castOther
						.getStrengthOfScheduleAdjEm2()) || (this
						.getStrengthOfScheduleAdjEm2() != null
						&& castOther.getStrengthOfScheduleAdjEm2() != null && this
						.getStrengthOfScheduleAdjEm2().equals(
								castOther.getStrengthOfScheduleAdjEm2())))
				&& ((this.getStrengthOfScheduleOppO() == castOther
						.getStrengthOfScheduleOppO()) || (this
						.getStrengthOfScheduleOppO() != null
						&& castOther.getStrengthOfScheduleOppO() != null && this
						.getStrengthOfScheduleOppO().equals(
								castOther.getStrengthOfScheduleOppO())))
				&& ((this.getStrengthOfScheduleOppO2() == castOther
						.getStrengthOfScheduleOppO2()) || (this
						.getStrengthOfScheduleOppO2() != null
						&& castOther.getStrengthOfScheduleOppO2() != null && this
						.getStrengthOfScheduleOppO2().equals(
								castOther.getStrengthOfScheduleOppO2())))
				&& ((this.getStrengthOfScheduleOppD() == castOther
						.getStrengthOfScheduleOppD()) || (this
						.getStrengthOfScheduleOppD() != null
						&& castOther.getStrengthOfScheduleOppD() != null && this
						.getStrengthOfScheduleOppD().equals(
								castOther.getStrengthOfScheduleOppD())))
				&& ((this.getStrengthOfScheduleOppD2() == castOther
						.getStrengthOfScheduleOppD2()) || (this
						.getStrengthOfScheduleOppD2() != null
						&& castOther.getStrengthOfScheduleOppD2() != null && this
						.getStrengthOfScheduleOppD2().equals(
								castOther.getStrengthOfScheduleOppD2())))
				&& ((this.getNcsosAdjEm() == castOther.getNcsosAdjEm()) || (this
						.getNcsosAdjEm() != null
						&& castOther.getNcsosAdjEm() != null && this
						.getNcsosAdjEm().equals(castOther.getNcsosAdjEm())))
				&& ((this.getNcsosAdjEm2() == castOther.getNcsosAdjEm2()) || (this
						.getNcsosAdjEm2() != null
						&& castOther.getNcsosAdjEm2() != null && this
						.getNcsosAdjEm2().equals(castOther.getNcsosAdjEm2())));
	}

	public int hashCode() {
		int result = 17;
		
		result = 37 * result
				+ (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getRank() == null ? 0 : this.getRank().hashCode());
		result = 37 * result
				+ (getTeam() == null ? 0 : this.getTeam().hashCode());
		result = 37 * result
				+ (getConf() == null ? 0 : this.getConf().hashCode());
		result = 37 * result + (getWL() == null ? 0 : this.getWL().hashCode());
		result = 37 * result
				+ (getAdjEm() == null ? 0 : this.getAdjEm().hashCode());
		result = 37 * result
				+ (getAdjO() == null ? 0 : this.getAdjO().hashCode());
		result = 37 * result
				+ (getAdjO2() == null ? 0 : this.getAdjO2().hashCode());
		result = 37 * result
				+ (getAdjD() == null ? 0 : this.getAdjD().hashCode());
		result = 37 * result
				+ (getAdjD2() == null ? 0 : this.getAdjD2().hashCode());
		result = 37 * result
				+ (getAdjT() == null ? 0 : this.getAdjT().hashCode());
		result = 37 * result
				+ (getAdjT2() == null ? 0 : this.getAdjT2().hashCode());
		result = 37 * result
				+ (getLuck() == null ? 0 : this.getLuck().hashCode());
		result = 37 * result
				+ (getLuck2() == null ? 0 : this.getLuck2().hashCode());
		result = 37
				* result
				+ (getStrengthOfScheduleAdjEm() == null ? 0 : this
						.getStrengthOfScheduleAdjEm().hashCode());
		result = 37
				* result
				+ (getStrengthOfScheduleAdjEm2() == null ? 0 : this
						.getStrengthOfScheduleAdjEm2().hashCode());
		result = 37
				* result
				+ (getStrengthOfScheduleOppO() == null ? 0 : this
						.getStrengthOfScheduleOppO().hashCode());
		result = 37
				* result
				+ (getStrengthOfScheduleOppO2() == null ? 0 : this
						.getStrengthOfScheduleOppO2().hashCode());
		result = 37
				* result
				+ (getStrengthOfScheduleOppD() == null ? 0 : this
						.getStrengthOfScheduleOppD().hashCode());
		result = 37
				* result
				+ (getStrengthOfScheduleOppD2() == null ? 0 : this
						.getStrengthOfScheduleOppD2().hashCode());
		result = 37
				* result
				+ (getNcsosAdjEm() == null ? 0 : this.getNcsosAdjEm()
						.hashCode());
		result = 37
				* result
				+ (getNcsosAdjEm2() == null ? 0 : this.getNcsosAdjEm2()
						.hashCode());
		return result;
	}

}
