package com.grape.models;
// Generated Dec 9, 2016 9:59:15 AM by Hibernate Tools 3.4.0.CR1


import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NbatableId generated by hbm2java
 */
@Entity
@Table(name = "ncaa_schedtable", catalog = "grape_db")
public class NcaaSchedule  implements java.io.Serializable {


     private String awayTeam;
     private String homeTeam;
     private Integer id;
     private String time;
     private String site;

    @Id
    @Column(name="Game_Id")
    public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="Away", length=65535)
    public String getAwayTeam() {
        return this.awayTeam;
    }
    
    public void setAwayTeam(String awayTeam) {
        this.awayTeam = awayTeam;
    }

    @Column(name="Home")
    public String getHomeTeam() {
        return this.homeTeam;
    }
    
    public void setHomeTeam(String homeTeam) {
        this.homeTeam = homeTeam;
    }

    @Column(name="Site")
    public String getSite() {
        return this.site;
    }
    
    public void setSite(String site) {
        this.site = site;
    }
    
    @Column(name="Time")
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NcaaSchedule) ) return false;
		 NcaaSchedule castOther = ( NcaaSchedule ) other; 
         
		 return ( (this.getAwayTeam()==castOther.getAwayTeam()) || ( this.getAwayTeam()!=null && castOther.getAwayTeam()!=null && this.getAwayTeam().equals(castOther.getAwayTeam()) ) )
 && ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getHomeTeam()==castOther.getHomeTeam()) || ( this.getHomeTeam()!=null && castOther.getHomeTeam()!=null && this.getHomeTeam().equals(castOther.getHomeTeam()) ) )
 && ( (this.getTime()==castOther.getTime()) || ( this.getTime()!=null && castOther.getTime()!=null && this.getTime().equals(castOther.getTime()) ) )
 && ( (this.getSite()==castOther.getSite()) || ( this.getSite()!=null && castOther.getSite()!=null && this.getSite().equals(castOther.getSite()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getAwayTeam() == null ? 0 : this.getAwayTeam().hashCode() );
         result = 37 * result + ( getHomeTeam() == null ? 0 : this.getHomeTeam().hashCode() );
         result = 37 * result + ( getSite() == null ? 0 : this.getSite().hashCode() );
         result = 37 * result + ( getTime() == null ? 0 : this.getTime().hashCode() );
         return result;
   }   


}


